### ISSUE TITLE
Créer ConnexionInscription

### ISSUE THREAD

**Issue by Fabien-Airaud** [NicolasZanin/Poseidon#11]
Fragment

- [ ] Bouton "Se connecter"
- [ ] Bouton "S'inscrire"
- [ ] Bouton croix pour quitter le fragment

![image](https://user-images.githubusercontent.com/115251193/231192519-712ccf00-d6a7-4520-811a-f64c72454243.png)

**Comment by arnaud18o5** [comment]
Pas besoin de la faire parce qu'on va se servir du service de google
