### ISSUE TITLE
Créer FormInscription

### ISSUE THREAD

**Issue by Fabien-Airaud** [NicolasZanin/Poseidon#12]
Fragment

- [ ] Titre "S'inscrire"
- [ ] Input "Nom"
- [ ] Input "Prénom"
- [ ] Input "Adresse mail"
- [ ] Input "Mot de passe"
- [ ] Input "Confirmer votre mot de passe"
- [ ] Boutons "Confirmer" et "Annuler"
- [ ] Bouton croix pour quitter le fragment

![image](https://user-images.githubusercontent.com/115251193/231193993-6acc67bc-e470-40e7-bb5a-718fd9f6de1e.png)

**Comment by AlexisMalosse** [comment]
Pas besoin de la faire parce qu'on va se servir du service de google
