### ISSUE TITLE
Créer FormConnexion

### ISSUE THREAD

**Issue by Fabien-Airaud** [NicolasZanin/Poseidon#13]
Fragment

- [ ] Titre "Se connecter"
- [ ] Input "Adresse mail"
- [ ] Input "Mot de passe"
- [ ] Case à cocher "Se souvenir de moi"
- [ ] Boutons "Confirmer" et "Annuler"
- [ ] Bouton croix pour quitter le fragment

![image](https://user-images.githubusercontent.com/115251193/231195419-371e2a3d-31a8-4f69-8108-6b0161c3ed95.png)

**Comment by AlexisMalosse** [comment]
Pas besoin de la faire parce qu'on va se servir du service de google
